### ISSUE TITLE
New opportunity notifications

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital_marketplace#118]
Hello guys!
I am subscribed for notifications of new opportunities under my Public Sector Employee account. Pretty sure I did not receive a notification about [this latest one](https://digital.gov.bc.ca/marketplace/opportunities/code-with-us/d359da07-d8e2-48eb-89bc-35f9f04aa09c/edit).

**Comment by dhruvio** [comment]
We needed to batch the notification emails that are being dispatched by the government email server. This fix has been implemented and deployed to production. Thanks @mark-a-wilson
