### ISSUE TITLE
Feature request: provide a way to view the Code With Us terms

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital_marketplace#126]
#### User Stories
As a **proponent**, I would like to see what the Code With Us terms are before deciding to apply on an opportunity.

As a **government administrator**, I need a way to send the Code With Us terms to my finance staff so that they have a copy of "the contract" and can set up a purchase order to pay invoices against it.

![terms](https://user-images.githubusercontent.com/16946297/91493772-a294e380-e86c-11ea-8dfc-92ac62f5cb3a.png)

**Comment by sutherlanda** [comment]
Hi @mark-a-wilson ,

The Terms and Conditions for both Code With Us and Sprint With Us can be viewed from your User Profile -> Accepted Policies, Terms & Agreements, if you have already accepted them.  You will also be presented with the Terms and Conditions when first signing into your User Profile as a new user.

Would this meeting the requirements for your feature request?

**Comment by sutherlanda** [comment]
@mark-a-wilson my apologies, it does appear that the CWU specific T&C are missing.  We have an issue in our backlog to address this.

**Comment by mark-a-wilson** [comment]
Thanks for the fast reply! ⚡️

I was just thinking it would be helpful for a user to able to read the terms while browsing the opportunity.

And for internal gov admin purposes, it's necessary to be able to screen print or download the terms as a document as we have to submit "the contract" to Finance via email w/ attachments, as well as file a copy on a secure LAN for records management requirements.

P.S. I am keeping [https://github.com/bcdevexchange/code-with-us](https://github.com/bcdevexchange/code-with-us) up-to-date with just the Terms in isolation. Have just updated that now. 

Cheers 🍻

**Comment by dhruvio** [comment]
This has been completed and deployed to production. The CWU terms are presented to vendors when they try to submit their CWU proposals (must check a box to accept before submitting). The terms are also published at this URL: https://digital.gov.bc.ca/marketplace/content/code-with-us-terms-and-conditions
