### ISSUE TITLE
Feature request: Link to codebase on GitHub

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital_marketplace#131]
### User Story
As a public sector employee from another jurisdiction (e.g. Government of Canada), I would like to know that the source code for the Digital Marketplace app is open source, so we can build our own!

(_This came from a conversation @ZachWoodward and I just had with some folks from [this Gov of Canada team](https://sara-sabr.github.io/ITStrategy/home.html). They had forked the old devex codebase, then visited digital.gov.bc.ca/marketplace, but it was not apparent  to them that the code for it was also open source._)

**Comment by dhruvio** [comment]
Thanks, @mark-a-wilson, will add a link to the footer

**Comment by dhruvio** [comment]
This has been completed and deployed to production.
