### ISSUE TITLE
Fix CSS issue causing some text to be transparent.

### ISSUE THREAD

**Issue by jleach** [bcgov/digital_marketplace#148]
On one of the [pages](https://digital.gov.bc.ca/marketplace/opportunities/sprint-with-us/cbcf9c02-3b1c-4c35-a42a-6478d6a0e902) of Sprint With Us projects some of the labels/text do not show up. You can however see them if you highlight the column in the table as shows in the screen shot below. You can see the `F/T` and `P/T` labels only show up when highlighted. Does not work in Safari or Chrome.

<img width="454" alt="Screen Shot 2021-02-26 at 5 19 22 PM" src="https://user-images.githubusercontent.com/390891/109370845-e20dae00-7856-11eb-9293-f167305178c3.png">

**Comment by dhruvio** [comment]
Thanks, @jleach, will add to the backlog

**Comment by dhruvio** [comment]
@jleach This issue has been fixed in the `development` branch. It will be merged into master during the next deploy.

**Comment by SteveChapmanBCDX** [comment]
Merged into `master` and promoted to Prod.
