### ISSUE TITLE
date picker fields don't work in Safari

### ISSUE THREAD

**Issue by mark-a-wilson** [bcgov/digital_marketplace#159]
Browser: Safari Version 14.0.3
Environments: TEST and PROD

Signed in as a public sector user, I started drafting a SWU opportunity. When I got to the **Proposal Deadline** and **Assignment Date** fields, I could not type anything into the fields, nor see any date picker.

**Comment by dhruvio** [comment]
Hi @mark-a-wilson — Safari introduced desktop support for the date picker in 14.1. The only solution to support old versions of desktop Safari is to implement a custom date picker. Given how tickets were prioritized by BCGov, this was seen to be a low priority issue given most users are on Chrome, especially now that Safari has fixed the issue on their end. Thanks!

**Comment by mark-a-wilson** [comment]
Thanks! Did not even notice my Safari is not up to date.
