### ISSUE TITLE
Migrate completed work from Button fork to BCGov repo

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital_marketplace#200]
Business value - we want to capture the work done and migrate to final repo.

The Button team completed work on a bunch of tech debt.  The work was done on the Button fork.

Details:
- [ ] Include config setting changes to match team agreements on Button fork
- [ ] Include cypress secrets
- [x] Include Sonar secrets

**Comment by SteveChapmanBCDX** [comment]
Hold put in place for now pending decision on way forward with DM application.  Once that decision is made, we'll review this issue.

**Comment by BCerki** [comment]
Started addressing here: https://github.com/button-inc/digital_marketplace/pull/142

**Comment by mikevespi** [comment]
@bdolor I've reverted all of the things that had question marks, notably devcontainers are gone, licenses restored to their original state. I'll leave it up to you if you want to give it another review. I'd suggest touching base with Vlad before you merge it just to make sure that he's not working on it but other than that it should be good to go. Let me know if you have any questions about it or requests.

**Comment by bdolor** [comment]
Thanks @mikevespi I'll give it another review.

**Comment by eazeredo** [comment]
For reference, issues #241 and #250 are included in PR #214.
