### ISSUE TITLE
CD/CI - Minimize production image size

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital_marketplace#201]
Business value:
* Right now, the production image applies Grunt later than optimal - if we applied Grunt earlier, we could reduce the size of the image
* Align with Test/Prod parity
* Eliminate existing anti-patterns (reduce tech debt)

Questions to answer:

- [ ] What is the current image size in production?
- [ ] What is the ideal image size?
- [ ] Who requested this?
- [ ] Why we should do this?

**Comment by bdolor** [comment]
https://github.com/bcgov/digital_marketplace/pull/283 reduces image size from 1.8GB to 1.19GB
