### ISSUE TITLE
Create Note - Opportunity History

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/digital_marketplace#203]
As an Opportunity Owner or Administrator
I want to add notes (text and/or multiple attachments) in the Opportunity history
So that I can provide a complete audit history if/when required

Opportunity owners and administrators require the ability to add a general note at the opportunity level.  In addition to the text provided for the note, the user may include an attachment, or attachments, to supplement the note.

Designs uploaded to InVision:

Page: Opportunity History -  https://invis.io/QBZ92HXTMJZ
Modal: Add Entry to Opportunity -  https://invis.io/QNZ92I36DAG

Original Jira ticket => https://bcdevex.atlassian.net/browse/DM-97
Unmerged PR => https://github.com/bcgov/digital_marketplace/pull/134

Related Jira ticket => https://bcdevex.atlassian.net/browse/DM-814
(There's no related PR for this issue)

**Acceptance Criteria:**

- [x] Validate to ensure that only PDF files can be added
- [x] Validate to ensure that only files less than or equal to 2 MB can be added
- [x] Validate to ensure that note field is not empty
- [x] Validate to ensure that note field is not greater than 1000 chars
- [x] Apply max length to note's text field (e.g., 1024 characters max)
- [x] Ensure that multiple attachments can be uploaded
- [x] On save, the field "Entity Type" has the value "Note".
- [ ] <s>All admins to be notified by email when a new note is add to a History List (template text requirements)</s>
- [x] Refresh the history list to show the new note

**Comment by BCerki** [comment]
Icon link: https://fontawesome.com/v5.15/icons/file-edit?style=solid

**Comment by BCerki** [comment]
@SteveChapmanBCDX, there's no limit on the note length in the db. Would you like there to be?

**Comment by SteveChapmanBCDX** [comment]
> @SteveChapmanBCDX, there's no limit on the note length in the db. Would you like there to be?

Good catch.  Yes, let's some reasonable limit.  Not sure what that might be.  2000 characters?

**Comment by BCerki** [comment]
@SteveChapmanBCDX, the designs and AC don't have direction for error handling. Does the following work for you?
- if the note is invalid (too short, wrong file format, etc.), in the modal, there's an error message and the submit button is greyed out like this:
![Screenshot from 2022-02-09 08-08-15](https://user-images.githubusercontent.com/77306764/153241928-bd209173-2c0b-4740-a266-6f4404e2638f.png)
- if there's a database error and the note doesn't save, you get a generic toast:
![Screenshot from 2022-02-09 08-13-48](https://user-images.githubusercontent.com/77306764/153242156-fb2d3eb9-7a1e-4a8a-8e87-5a01aabe32de.png)

**Comment by SteveChapmanBCDX** [comment]
@BCerki - Yes, this looks good.

**Comment by BCerki** [comment]
> > @SteveChapmanBCDX, there's no limit on the note length in the db. Would you like there to be?
> 
> Good catch. Yes, let's some reasonable limit. Not sure what that might be. 2000 characters?

@SteveChapmanBCDX, we found a place where the previous developers limited the note to 1000 characters. Would you like to go with that?
