### ISSUE TITLE
Automate Changelog Generation

### ISSUE THREAD

**Issue by wenzowski** [bcgov/digital_marketplace#236]
We discussed in button-inc/digital_marketplace#14 but haven't implemented yet in our first branching model agreements button-inc/digital_marketplace#18, the opportunity to adopt and enforce Conventional Commits. Might we consider enforcing that with a [Gitlint](https://jorisroovers.com/gitlint/) guardrail ([sample config](https://github.com/bcgov/cas-ciip-portal/blob/develop/.gitlint)) in a pre-commit hook ([sample config](https://github.com/bcgov/cas-ciip-portal/blob/develop/.pre-commit-config.yaml#L35))? This would unblock the option of using [standard-version](https://github.com/conventional-changelog/standard-version) to automate the release process in a manner compliant with [SemVer](https://semver.org/). If this adds value to our process, we'd likely want a releasing team agreement ([sample agreement](https://github.com/bcgov/cas-ciip-portal/blob/develop/docs/release.md)) to be part of this issue.

**Comment by BCerki** [comment]
We're using conventional commits now, so:

As a developer
I want to automate changelog generation
so that I don't have to do it manually.

Tasks:
- [ ] automate changelog generation in a manner compliant with SemVer

**Comment by bdolor** [comment]
addressed in https://github.com/bcgov/digital_marketplace/pull/288/
