### ISSUE TITLE
SWU - Update the Proposal status when a Opportunity is Awarded | DM-717

### ISSUE THREAD

**Issue by eazeredo** [bcgov/digital_marketplace#241]
FEATURE: Award the opportunity winner

GIVEN an opportunity with the state "Evaluation Team Scenario"
WHEN I choose the winner proponent and Save
THEN the opportunity state is updated to "Awarded" 
AND the winner proponent status is changed to "Awarded"
AND an email is sent to the winner and another to the other proponents
**AND the other proponents status are changed for Gov and Vendor to "Not Awarded" <--- this is new**

WHEN the proponent status is changed to "Awarded"
THEN ...

WHEN the proponent status is changed to "Not Awarded"
THEN ...

----

If a SWU proposal does not get screened in through all stages of a SWU opportunity and the opportunity is awarded to another SWU proposal, the unsuccessful proposal's status is not being updated correctly.

For example, a proposal is screened in to the Code Challenge stage of a SWU opportunity, but the proponent fails this stage.  They are not disqualified and the proposal is not withdrawn; therefore, the status remains as “Evaluated (CC)”.  This status should be updated to “Not Awarded” once the opportunity has been awarded to the successful proponent.  

Currently, the status is presented as:

- "Under Review" for Vendor
- "Evaluated (stage)" for Gov 

The status should be presented as:

- "Not Awarded" for Vendor
- "Not Awarded" for Gov

I have attached screenshots for the current state for both Vendor and Gov users.

---
Original issue with images: https://bcdevex.atlassian.net/browse/DM-717

**Comment by BCerki** [comment]
See PR: https://github.com/button-inc/digital_marketplace/pull/140

**Comment by mikevespi** [comment]
This is done and well tested  in Cypress on the Button fork. Today I will be creating a PR on the government repo with only the code that fixes the problem, as the rest of the cypress code only exists on the Button fork.

**Comment by mikevespi** [comment]
The code has been merged to button fork, so this will get merged to BCGov repo with the button fork.
