### ISSUE TITLE
Assess the database size in production

### ISSUE THREAD

**Issue by eazeredo** [bcgov/digital_marketplace#247]
During the implementation of #203, the team identified that the files are being saved into the database instead of to external storage and having only the file pointer saved in the database.

The concern is if the database reaches the limit, any information could be added, and the application could potentially crash.

The task is:
[ ] Verify the current database size in the production environment
[ ] Verify the database size limit in the production environment

**Comment by eazeredo** [comment]
@bdolor , could you help us with these questions as we don't have access to production? Or point someone who could extract this information?

**Comment by bdolor** [comment]
current db size in production env: 
```
digmkt=> select pg_size_pretty(pg_database_size('digmkt'));
 pg_size_pretty 
----------------
 262 MB
(1 row)
```

size of tables (limit 20) in descending order: 
```
         relation         | total_size 
--------------------------+------------
 fileBlobs                | 240 MB
 swuOpportunityVersions   | 2752 kB
 swuTeamQuestions         | 1896 kB
 cwuOpportunityVersions   | 1496 kB
 swuTeamQuestionResponses | 1256 kB
 users                    | 1080 kB
 swuPhaseCapabilities     | 1008 kB
 cwuProposals             | 688 kB
 swuOpportunityPhases     | 352 kB
 affiliations             | 312 kB
 cwuProposalStatuses      | 296 kB
 sessions                 | 224 kB
 swuProposalStatuses      | 208 kB
 swuProposalTeamMembers   | 208 kB
 cwuOpportunityStatuses   | 208 kB
 files                    | 184 kB
 swuOpportunityStatuses   | 176 kB
 contentVersions          | 168 kB
 swuOpportunityAddenda    | 144 kB
 organizations            | 136 kB
(20 rows)
```
size of persistent volume claim for each patroni pod is `10Gi` https://github.com/bcgov/digital_marketplace/blob/development/openshift/templates/database/patroni-digmkt-deploy.yaml#L246 

storage quotas for the namespace are currently defined by `storage-64` https://developer.gov.bc.ca/Project-Resource-Quotas-in-BC-Gov's-PaaS-(Openshift-4-Platform)
