### ISSUE TITLE
patroni stability 

### ISSUE THREAD

**Issue by bdolor** [bcgov/digital_marketplace#251]
- patroni version currently installed on prod: 

<img width="204" alt="image" src="https://user-images.githubusercontent.com/2048170/155214270-d27cb8ad-faca-4701-98ed-3ad32de71fcd.png">

Will need to apply the issue hot fix outlined here prior to March 7: 
- https://github.com/BCDevOps/openshift-wiki/blob/master/docs/HowTo/UpdatePatroni.md

**Comment by bdolor** [comment]
<img width="191" alt="image" src="https://user-images.githubusercontent.com/2048170/156668925-9ab328d5-2bed-48fa-9604-1fa3934fd618.png">

complete

**Comment by SteveChapmanBCDX** [comment]
Reopening to connect related issue.
