### ISSUE TITLE
Display who won the opportunity

### ISSUE THREAD

**Issue by jleach** [bcgov/digital_marketplace#289]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd suggest**

Since it's a matter of public record, it would be good to see who won an opportunity.

**Describe alternatives you've considered**

Alternatives at this time would include a FOI for contract details. This is a bit heavy handed and expensive for the government. Better to be open.

**Additional context**

None

**Comment by bdolor** [comment]
This functionality is already available to both authenticated and unauthenticated users. Opportunities->Closed Opportunities and click on any closed opportunity. The successful proponent is listed at the top.

**Comment by jleach** [comment]
Thanks for pointing that out!
